### ISSUE TITLE
KV Hamburg: No symptoms shown on start page, TTT in wrong order

### ISSUE THREAD

**Issue by bzoch-lesniak** [zidatalab/ambulante_notfaelle#34]
Bei KV Hamburg wird die Abbildung "Häufigste Beschwerden" nicht angezeigt und bei der Abbildung Dringlichkeit ist die Reihenfolge der Balken durcheinander. Bei KVMV ist die Reihenfolge bei der Dringlichkeit auch anders als sonst (oberster Balken = k.A., dieser ist sonst immer unten)

**Comment by Inoakabu** [comment]
It looks like we're not getting any data regarding mainsymptoms_ts when Hamburg is selected

@anjaseidel or @KodjoV maybe one of you could check it directly on the DB?

**Comment by Inoakabu** [comment]
Addition:

The Problem seems to be more regarding the resolution for "monthly" and "weekly". If you choose "weekly" it works
Could still maybe a problem with the data in DB

**Comment by Inoakabu** [comment]
Alright alright alright - Guess I fixed it. The problem was that there was one month without any data for mainsymptoms and that killed the whole thing. I now add an empty array for mainsymptoms for all month item without data.

Maybe a thing to populate an empty array if no data right from the api request?
